### ISSUE TITLE
[Feature] arm32 build

### ISSUE THREAD

**Issue by hooddy** [henrypp/iplookup#7]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

1.7.3

### Problem you are trying to solve

i wanna to ask for aarm32 build

### Suggested solution

there is arm64 build. so i am just though why not? i have arm32 tab still.

**Comment by henrypp** [comment]
no,you can do it yourself
